# Generated by Django 4.0.3 on 2022-03-09 10:26

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('location', djgeojson.fields.PolygonField()),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('code', models.SlugField(default='xxx', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=225, null=True)),
                ('location', djgeojson.fields.PointField()),
                ('date_added', models.DateField()),
                ('region1', models.CharField(blank=True, max_length=50, null=True)),
                ('region2', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('link_caption', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
