# Generated by Django 4.0.3 on 2022-03-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
