# Generated by Django 4.0.3 on 2022-04-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Weather',
            fields=[
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.site')),
                ('last_updated', models.DateField()),
                ('wind', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date',)},
        ),
    ]
