# Generated by Django 4.0.3 on 2022-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_rename_site_weather_siteweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteweather',
            name='slug',
            field=models.SlugField(default='nmf', unique=True),
            preserve_default=False,
        ),
    ]
