# Generated by Django 4.0.3 on 2022-04-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_siteweather_wind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteweather',
            name='wind',
            field=models.TextField(blank=True, null=True),
        ),
    ]
