# Generated by Django 4.0.3 on 2022-04-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_siteweather_wind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteWeather',
        ),
    ]
