# Generated by Django 4.0.3 on 2022-04-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0012_delete_siteweather'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteWeather',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.site')),
                ('slug', models.SlugField(unique=True)),
                ('last_updated', models.DateField()),
                ('wind', models.TextField(blank=True, null=True)),
                ('weather', models.JSONField()),
                ('weather_updated', models.DateTimeField()),
            ],
        ),
    ]
