# Generated by Django 4.0.3 on 2022-04-07 15:53

import datetime
from django.db import migrations, models
import weather.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_siteweather_weather_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteweather',
            name='last_updated',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='siteweather',
            name='weather_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 23, 53, 38, 229184)),
        ),
        migrations.AlterField(
            model_name='siteweather',
            name='wind',
            field=models.TextField(blank=True, default=weather.models.wind_default, null=True),
        ),
    ]
