# Generated by Django 4.0.3 on 2022-04-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_siteweather_swell_marginal_siteweather_swell_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteweather',
            name='weather_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
