# Generated by Django 4.0.3 on 2022-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_siteweather_weather_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteweather',
            name='swell_marginal',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.3, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='siteweather',
            name='swell_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=2.5, max_digits=3, null=True),
        ),
    ]
